@Backend_HostAddress = https://localhost:7243

GET {{Backend_HostAddress}}/shortener/availableurls

###

POST {{Backend_HostAddress}}/shortener/shortenurl
Content-Type: application/json
{
  "url": "https://google.com"
}

###



@id=6tHOR
GET {{Backend_HostAddress}}/shortener/{{id}}

###

GET {{Backend_HostAddress}}/shortener/geturl/{{id}}

###
