// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShortenerAPI.Models;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(ShortenerContext))]
    partial class ShortenerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("ShortenerAPI.Models.ShortenedURL", b =>
                {
                    b.Property<string>("ShortURLId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Base64QRCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ShortURLId");

                    b.ToTable("ShortenedURLs");
                });
#pragma warning restore 612, 618
        }
    }
}
